services:
    - docker
language: bash
script:
    # build image
    - docker build -t alexadhy/rpi-postgresql-alpine:build .
    # test image
    - docker run alexadhy/rpi-postgresql-alpine:build psql --version
    # push image
    - DOCKER_TAG=$(grep "postgresql==" Dockerfile | sed 's/.*=//' | sed 's/-r.*//')
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker tag alexadhy/rpi-postgresql-alpine:build alexadhy/rpi-postgresql-alpine:$DOCKER_TAG
    - docker push alexadhy/rpi-postgresql-alpine:$DOCKER_TAG
